name = "TUN Respawn System v1.2.0";
picture = "Data\afilogo.paa";
actionName = "Community Website";
action = "https://armafinland.fi/";
description = "Wave respawn system";
logo = "Data\afilogo.paa";
logoOver = "Data\afilogo.paa";
logoSmall = "Data\afilogo.paa";
tooltip = "Customisable wave based respawn system";
tooltipOwned = "TUN Respawn System";
overview = "TUN Respawn System v1.2.0";
author = "Tuntematon";
//overviewPicture = "";
overviewText = "TUN Respawn System v1.2.0";
//overviewFootnote = "<br /><br /><t color='#999999'>Teksti<t />";